import colour
import numpy as np

# Requirements:
# pip install colour-science numpy

# Suppress warnings
import warnings
warnings.filterwarnings("ignore")

def get_matrix_flat(source_space, target_space_name):
    try:
        target_space = colour.RGB_COLOURSPACES[target_space_name]
        # Calculate Matrix: ProPhoto (D50) -> Target (Usually D65)
        # Using Bradford Chromatic Adaptation
        matrix = colour.matrix_RGB_to_RGB(
            source_space,
            target_space,
            chromatic_adaptation_transform='Bradford'
        )
        # Flatten and round for JS
        return [float(f"{x:.6f}") for x in matrix.flatten()]
    except KeyError:
        print(f"Error: Color space '{target_space_name}' not found.")
        return None

def main():
    # Define ProPhoto RGB (ROMM RGB)
    prophoto = colour.RGB_COLOURSPACES['ROMM RGB']

    # Mapping of UI keys to colour-science names
    mappings = {
        'Arri LogC3': 'ARRI Wide Gamut 3',
        'F-Log': 'F-Gamut',
        'F-Log2': 'F-Gamut', # F-Log2 typically uses F-Gamut
        'F-Log2 C': 'F-Gamut C',
        'S-Log3': 'S-Gamut3',
        'S-Log3.Cine': 'S-Gamut3.Cine',
        'V-Log': 'V-Gamut',
        'Canon Log 2': 'Cinema Gamut',
        'Canon Log 3': 'Cinema Gamut', # Canon Log 2/3 share Cinema Gamut
        'N-Log': 'ITU-R BT.2020', # N-Log uses BT.2020 primaries
        'D-Log': 'DJI D-Gamut',
        'Log3G10': 'REDWideGamutRGB'
    }

    print("// Generated by raw-alchemy-web/scripts/generate_matrices.py")
    print("export const GAMUT_MATRICES = {")

    keys = list(mappings.keys())
    for i, key in enumerate(keys):
        colour_science_name = mappings[key]
        matrix = get_matrix_flat(prophoto, colour_science_name)

        if matrix:
            # Format as a nice block
            m = matrix
            print(f"    // {colour_science_name}")
            print(f"    '{key}': [")
            print(f"        {m[0]}, {m[1]}, {m[2]},")
            print(f"        {m[3]}, {m[4]}, {m[5]},")
            print(f"        {m[6]}, {m[7]}, {m[8]}")

            # Add comma if not last item
            if i < len(keys) - 1:
                print("    ],")
            else:
                print("    ]")

    print("};")

if __name__ == "__main__":
    main()
